# This file was generated by GoReleaser. DO NOT EDIT.
cask "capiko-ai" do
  version "1.14.0"

  on_macos do
    on_intel do
      sha256 "27e02164e213d3042447a62c81a114555e22410ca52741e3cc488e945904bfa9"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c61b1e7ea4374944258fe8353e425d542d3502ac2da1ede8cac965860c64fc2c"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5a4ae34b2a11b9335782a42650c8d55facbb203f908cdeb5cc6df258bbdf4cff"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa614fdebc7a008f05a12806cd5f75688fe5bc6cba50d09a59d5df7e3e4cbf15"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capiko-ai"
  desc "capiko-ai — mounts the capiko layer (skills, state, backups) onto the GitHub Copilot CLI."
  homepage "https://github.com/martinhg/capiko-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capiko-ai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capiko-ai"]
    end
  end

  # No zap stanza required

end
