# This file was generated by GoReleaser. DO NOT EDIT.
cask "capiko-ai" do
  version "1.12.0"

  on_macos do
    on_intel do
      sha256 "79c930071ff19e4a8a3346e74f586e43ac9d460b628499bd03e33a02d2adf568"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01f896c7c0bd02028035b0a241570c2ecb91d692f25e53de1da93cb69c797ca8"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88883bff44f658218cf33ce6d78d2a88cff6d7f807b9cdc5eef17cc9cb54c5fa"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d797c146bfd6957e6b169eb4bee76f9a26b4ccdabb7abed6c01c61a2fce0fdd"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capiko-ai"
  desc "capiko-ai — mounts the capiko layer (skills, state, backups) onto the GitHub Copilot CLI."
  homepage "https://github.com/martinhg/capiko-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capiko-ai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capiko-ai"]
    end
  end

  # No zap stanza required

end
