# This file was generated by GoReleaser. DO NOT EDIT.
cask "capiko-ai" do
  version "1.11.0"

  on_macos do
    on_intel do
      sha256 "cf2a98488808dece67660fe38f0d11c2ddbaa1ac7b5f0e5387848597761c732b"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2bfd7447fcd27aaa8b1791685adb07c382cc06db8e2fb2d708c067653c778843"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4439d5db1eec8b3247851e4e400beb233de3784d0661bf5b1a407795a02eed61"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cbc08ee7a77daee03935708bf3421b909fec12537b7f378e527a215f8d2921b"
      url "https://github.com/martinhg/capiko-ai/releases/download/v#{version}/capiko-ai_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capiko-ai"
  desc "capiko-ai — mounts the capiko layer (skills, state, backups) onto the GitHub Copilot CLI."
  homepage "https://github.com/martinhg/capiko-ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capiko-ai"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capiko-ai"]
    end
  end

  # No zap stanza required

end
