# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CapikoAi < Formula
  desc "capiko-ai — mounts the capiko layer (skills, state, backups) onto the GitHub Copilot CLI."
  homepage "https://github.com/martinhg/capiko-ai"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/martinhg/capiko-ai/releases/download/v1.1.0/capiko-ai_1.1.0_darwin_amd64.tar.gz"
      sha256 "e81a51fedfe4670960d89c8e6147ffbe3fabd02aaa2b254a576b91765a3ee7dd"

      define_method(:install) do
        bin.install "capiko-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/martinhg/capiko-ai/releases/download/v1.1.0/capiko-ai_1.1.0_darwin_arm64.tar.gz"
      sha256 "789a9aa27acbba8406209ac18b5be578ef98f55c19344a8aceee39dadff69249"

      define_method(:install) do
        bin.install "capiko-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinhg/capiko-ai/releases/download/v1.1.0/capiko-ai_1.1.0_linux_amd64.tar.gz"
      sha256 "445d2d8d5c8d9d44d46ccadbfe53058101e562415cd8f5ffa96d5f136857413c"
      define_method(:install) do
        bin.install "capiko-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinhg/capiko-ai/releases/download/v1.1.0/capiko-ai_1.1.0_linux_arm64.tar.gz"
      sha256 "896cb0ecde498ffdaa8a78e54113cb0e58de729f5e9106b99600ec180a3fe871"
      define_method(:install) do
        bin.install "capiko-ai"
      end
    end
  end
end
